version: '1.0.{build}'

image: Ubuntu2004

stack: jdk 17, postgresql

environment:
  # these variables are common to all jobs
  PGUSER: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: "articles"
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  DB_URL: "jdbc:postgresql://localhost:5432/articles"

test_script:
  - cd my-site-back
  - mvn test -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener
