version: '1.0.{build}'

image: Ubuntu2004

stack: jdk openjdk-17

environment:
  # these variables are common to all jobs
  PGUSER: postgres
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  DB_URL: "jdbc:postgresql://127.0.0.1/articles"

services:
  - postgresql
init:
  - sudo sed -i -E -e 's/(local\s+all\s+postgres\s+)peer/\1trust/' /etc/postgresql/14/main/pg_hba.conf
test_script:
  - psql -U postgres -c 'create database articles;'
  - sudo -u postgres psql -c "ALTER ROLE postgres WITH password 'postgres'"
  - cd my-site-back
  - mvn test -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener
