version: '1.0.{build}'

image: Ubuntu2004

stack: jdk 17, postgresql

cache:
  - "$HOME/.cache"
  - "$HOME/.m2/repository"
  - "$HOME/.m2/wrapper"

environment:
  # these variables are common to all jobs
  POSTGRES_DB: "articles"
  DB_USERNAME: postgres
  DB_PASSWORD: "Password12!"
  DB_URL: "jdbc:postgresql://localhost:5432/articles"

install:
  - sh: |
      if [[ -d /usr/lib/jvm/java-17-openjdk-amd64 ]]; then sudo ln -s /usr/lib/jvm/java-17-openjdk-amd64 /usr/lib/jvm/java-17-openjdk; fi;
      export JAVA_HOME="/usr/lib/jvm/java-17-openjdk";
      export PATH="$JAVA_HOME:$PATH";
  - sh: |
      if [[ -z "${MAVEN_OPTS}" ]]; then export MAVEN_OPTS="-Dmaven.repo.local=.m2/repository -DprofileFormat=JSON,HTML -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener"; fi;
      if [[ -d ${HOME}/.m2 ]]; then rm -rf ${HOME}/.m2/repository/top/infra/maven; ls -ahl ${HOME}/.m2; fi;
      export MAVEN_USER_HOME="${PWD}/.m2";
      cd my-site-back;
      ./mvnw ${MAVEN_GLOBAL_SETTINGS} -version;
      mvn -version
  - sh: |
      export PGUSER=postgres
      export POSTGRES_USER=postgres
      export PGPASSWORD="Password12!"
      export POSTGRES_PASSWORD="Password12!"
      export PATH="/usr/bin/postgres:$PATH"
      

test_script:
  - ps -ef | grep postgres
  - psql -U postgres -c "create database articles;"
  - ./mvnw -B ${MAVEN_GLOBAL_SETTINGS} test

build: off