task:
  name: "Test-back"
  env:
    DB_USERNAME: "dbuser"
    DB_PASSWORD: "dbpass"
    DB_URL: "jdbc:postgresql://localhost:5432/articles"
  container:
    image: maven:3.8.1-openjdk-17-slim
    additional_containers:
      - name: postgres
        image: postgres
        env:
          POSTGRES_USER: "dbuser"
          POSTGRES_PASSWORD: "dbpass"
          POSTGRES_DB: "articles"
        port: 5432
  test-script:
    - cd my-site-back
    - mvn test -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener
  always:
    junit_artifacts:
      path: "my-site-back/target/surefire-reports/TEST-*.xml"
      type: text/xml
      format: junit