sudo: enabled
language: java

jdk: openjdk-17

services:
  - postgresql

jobs:
  include:
    - language: java
      jdk: openjdk-17
      env:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_URL=jdbc:postgresql://127.0.0.1/articles
      before_script:
      - cd my-site-back
      - psql -c "create database articles;" -U postgres
      - sudo -u postgres psql -c "ALTER ROLE postgres WITH password 'postgres'"
      script:
      - cd my-site-back
      - mvn test
      

