name: CI
run-name: ${{ github.event.head_commit.message }}
on: [push]
jobs:
  build-back:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: cd my-site-back
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verifyrun